-- MySQL Script generated by MySQL Workbench
-- Thu Dec  9 19:39:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artist` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Album` (
  `Name` VARCHAR(45) NOT NULL,
  `released date` DATE NULL,
  PRIMARY KEY (`Name`),
  CONSTRAINT `name`
    FOREIGN KEY (`Name`)
    REFERENCES `mydb`.`Artist` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Song` (
  `Title` VARCHAR(45) NOT NULL,
  `Artist` VARCHAR(45) NOT NULL,
  `release date` DATE NULL,
  PRIMARY KEY (`Title`, `Artist`),
  CONSTRAINT `album name`
    FOREIGN KEY (`Title`)
    REFERENCES `mydb`.`Album` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Song Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Song Genre` (
  `song name` VARCHAR(45) NOT NULL,
  `genre name` VARCHAR(45) NOT NULL,
  INDEX `song name_idx` (`song name` ASC) VISIBLE,
  INDEX `genre name_idx` (`genre name` ASC) VISIBLE,
  CONSTRAINT `song name`
    FOREIGN KEY (`song name`)
    REFERENCES `mydb`.`Song` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `genre name`
    FOREIGN KEY (`genre name`)
    REFERENCES `mydb`.`Genre` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rating` (
  `rating` SMALLINT NOT NULL,
CONSTRAINT `song name`
    FOREIGN KEY (`song name`)
    REFERENCES `mydb`.`Song` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `album name`
	FOREIGN KEY(`album name`)
    REFERENCES `mydb`.`Album` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `playlist name`
	FOREIGN KEY (`playlist name`)
    REFERENCES `mydb`.`Playlist` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Playlist` (
  `Title` VARCHAR(45) NOT NULL,
  `song name` VARCHAR(45) NULL,
  `date made` DATE NOT NULL,
  PRIMARY KEY (`Title`, `date made`),
  INDEX `song names_idx` (`song name` ASC) VISIBLE,
  CONSTRAINT `song names`
    FOREIGN KEY (`song name`)
    REFERENCES `mydb`.`Song` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;